saleor/cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update/(?P<variant_id>\d+)/$', views.update, name='update-line'),
    url(r'^summary/$', views.summary, name='cart-summary'),
    url(r'^shipingoptions/$', views.get_shipping_options,
        name='shipping-options')]

saleor/checkout/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^shipping-address/', views.shipping_address_view,
        name='shipping-address'),
    url(r'^shipping-method/', views.shipping_method_view,
        name='shipping-method'),
    url(r'^summary/', views.summary_view, name='summary'),
    url(r'^remove_voucher/', views.discount.remove_voucher_view,
        name='remove-voucher'),
    url(r'^login/', views.login, name='login')]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import JavaScriptCatalog
from django.contrib import admin
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^superadmin/', admin.site.urls),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^impersonate/', include('impersonate.urls')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^profile/',
        include((userprofile_urls, 'profile'), namespace='profile')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search')),
    url(r'^mobile/', include("saleor.mobile.urls")),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/cart/models.py
"""Cart-related ORM models."""
from collections import namedtuple
from decimal import Decimal
from uuid import uuid4

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.encoding import smart_str
from django.utils.timezone import now
from django.utils.translation import pgettext_lazy
from django_prices.models import PriceField
from jsonfield import JSONField
from prices import Price
from satchless.item import ItemLine, ItemList, partition

from . import CartStatus, logger

CENTS = Decimal('0.01')
SimpleCart = namedtuple('SimpleCart', ('quantity', 'total', 'token'))


def find_open_cart_for_user(user):
    """Find an open cart for the given user."""
    carts = user.carts.open()
    if len(carts) > 1:
        logger.warning('%s has more than one open basket', user)
        for cart in carts[1:]:
            cart.change_status(CartStatus.CANCELED)
    return carts.first()


class ProductGroup(ItemList):
    """A group of products."""

    def is_shipping_required(self):
        """Return `True` if any product in group requires shipping."""
        return any(p.is_shipping_required() for p in self)


class CartQueryset(models.QuerySet):
    """A specialized queryset for dealing with carts."""

    def anonymous(self):
        """Return unassigned carts."""
        return self.filter(user=None)

    def open(self):
        """Return `OPEN` carts."""
        return self.filter(status=CartStatus.OPEN)

    def saved(self):
        """Return `SAVED` carts."""
        return self.filter(status=CartStatus.SAVED)

    def waiting_for_payment(self):
        """Return `SAVED_FOR_PAYMENT` carts."""
        return self.filter(status=CartStatus.WAITING_FOR_PAYMENT)

    def checkout(self):
        """Return carts in `CHECKOUT` state."""
        return self.filter(status=CartStatus.CHECKOUT)

    def canceled(self):
        """Return `CANCELED` carts."""
        return self.filter(status=CartStatus.CANCELED)

    def for_display(self):
        """Annotate the queryset for display purposes.

        Prefetches additional data from the database to avoid the n+1 queries
        problem.
        """
        return self.prefetch_related(
            'lines__variant__product__categories',
            'lines__variant__product__images',
            'lines__variant__product__product_class__product_attributes__values',  # noqa
            'lines__variant__product__product_class__variant_attributes__values',  # noqa
            'lines__variant__stock')


class Cart(models.Model):
    """A shopping cart."""

    status = models.CharField(
        pgettext_lazy('Cart field', 'order status'),
        max_length=32, choices=CartStatus.CHOICES, default=CartStatus.OPEN)
    created = models.DateTimeField(
        pgettext_lazy('Cart field', 'created'), auto_now_add=True)
    last_status_change = models.DateTimeField(
        pgettext_lazy('Cart field', 'last status change'), auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, related_name='carts',
        verbose_name=pgettext_lazy('Cart field', 'user'),
        on_delete=models.CASCADE)
    email = models.EmailField(
        pgettext_lazy('Cart field', 'email'), blank=True, null=True)
    token = models.UUIDField(
        pgettext_lazy('Cart field', 'token'),
        primary_key=True, default=uuid4, editable=False)
    voucher = models.ForeignKey(
        'discount.Voucher', null=True, related_name='+',
        on_delete=models.SET_NULL,
        verbose_name=pgettext_lazy('Cart field', 'token'))
    checkout_data = JSONField(
        verbose_name=pgettext_lazy('Cart field', 'checkout data'), null=True,
        editable=False,)
    total = PriceField(
        pgettext_lazy('Cart field', 'total'),
        currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2,
        default=0)
    quantity = models.PositiveIntegerField(
        pgettext_lazy('Cart field', 'quantity'), default=0)

    objects = CartQueryset.as_manager()

    class Meta:
        ordering = ('-last_status_change',)

    def __init__(self, *args, **kwargs):
        self.discounts = kwargs.pop('discounts', None)
        super(Cart, self).__init__(*args, **kwargs)

    def update_quantity(self):
        """Recalculate cart quantity based on lines."""
        total_lines = self.count()['total_quantity']
        if not total_lines:
            total_lines = 0
        self.quantity = total_lines
        self.save(update_fields=['quantity'])

    def change_status(self, status):
        """Change cart status."""
        # FIXME: investigate replacing with django-fsm transitions
        if status not in dict(CartStatus.CHOICES):
            raise ValueError('Not expected status')
        if status != self.status:
            self.status = status
            self.last_status_change = now()
            self.save()

    def change_user(self, user):
        """Assign cart to a user.

        If the user already has an open cart assigned, cancel it.
        """
        open_cart = find_open_cart_for_user(user)
        if open_cart is not None:
            open_cart.change_status(status=CartStatus.CANCELED)
        self.user = user
        self.save(update_fields=['user'])

    def is_shipping_required(self):
        """Return `True` if any of the lines requires shipping."""
        return any(line.is_shipping_required() for line in self.lines.all())

    def __repr__(self):
        return 'Cart(quantity=%s)' % (self.quantity,)

    def __len__(self):
        return self.lines.count()

    # pylint: disable=R0201
    def get_subtotal(self, item, **kwargs):
        """Return the cost of a cart line."""
        return item.get_total(**kwargs)

    def get_total(self, **kwargs):
        """Return the total cost of the cart prior to shipping."""
        subtotals = [
            self.get_subtotal(item, **kwargs) for item in self.lines.all()]
        if not subtotals:
            raise AttributeError('Calling get_total() on an empty item set')
        zero = Price(0, currency=settings.DEFAULT_CURRENCY)
        return sum(subtotals, zero)

    def count(self):
        """Return the total quantity in cart."""
        lines = self.lines.all()
        return lines.aggregate(total_quantity=models.Sum('quantity'))

    def clear(self):
        """Remove the cart."""
        self.delete()

    def create_line(self, variant, quantity, data):
        """Create a cart line for given variant, quantity and optional data.

        The `data` parameter may be used to differentiate between items with
        different customization options.
        """
        return self.lines.create(
            variant=variant, quantity=quantity, data=data or {})

    def get_line(self, variant, data=None):
        """Return a line matching the given variant and data if any."""
        all_lines = self.lines.all()
        if data is None:
            data = {}
        line = [line for line in all_lines
                if line.variant_id == variant.id and line.data == data]
        if line:
            return line[0]

    def add(self, variant, quantity=1, data=None, replace=False,
            check_quantity=True):
        """Add a product vartiant to cart.

        The `data` parameter may be used to differentiate between items with
        different customization options.

        If `replace` is truthy then any previous quantity is discarded instead
        of added to.
        """
        cart_line, dummy_created = self.lines.get_or_create(
            variant=variant, defaults={'quantity': 0, 'data': data or {}})
        if replace:
            new_quantity = quantity
        else:
            new_quantity = cart_line.quantity + quantity

        if new_quantity < 0:
            raise ValueError('%r is not a valid quantity (results in %r)' % (
                quantity, new_quantity))

        if check_quantity:
            variant.check_quantity(new_quantity)

        cart_line.quantity = new_quantity

        if not cart_line.quantity:
            cart_line.delete()
        else:
            cart_line.save(update_fields=['quantity'])
        self.update_quantity()

    def partition(self):
        """Split the card into a list of groups for shipping."""
        grouper = (
            lambda p: 'physical' if p.is_shipping_required() else 'digital')
        return partition(self.lines.all(), grouper, ProductGroup)


class CartLine(models.Model, ItemLine):
    """A single cart line.

    Multiple lines in the same cart can refer to the same product variant if
    their `data` field is different.
    """

    cart = models.ForeignKey(
        Cart, related_name='lines',
        verbose_name=pgettext_lazy('Cart line field', 'cart'),
        on_delete=models.CASCADE)
    variant = models.ForeignKey(
        'product.ProductVariant', related_name='+',
        verbose_name=pgettext_lazy('Cart line field', 'product'),
        on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(
        pgettext_lazy('Cart line field', 'quantity'),
        validators=[MinValueValidator(0), MaxValueValidator(999)])
    data = JSONField(
        blank=True, default={},
        verbose_name=pgettext_lazy('Cart line field', 'data'))

    class Meta:
        unique_together = ('cart', 'variant', 'data')

    def __str__(self):
        return smart_str(self.variant)

    def __eq__(self, other):
        if not isinstance(other, CartLine):
            return NotImplemented

        return (self.variant == other.variant and
                self.quantity == other.quantity and
                self.data == other.data)

    def __ne__(self, other):
        return not self == other  # pragma: no cover

    def __repr__(self):
        return 'CartLine(variant=%r, quantity=%r, data=%r)' % (
            self.variant, self.quantity, self.data)

    def __getstate__(self):
        return self.variant, self.quantity, self.data

templates/cart/_subtotal_table.html
{% load i18n %}
{% load price_range from price_ranges %}
{% load gross from prices_i18n %}

{% if shipping_required %}
  <div class="table__row">
    <div class="row">
      <div class="col-8 cart__total__subtotal">
        <h3>{% trans "Subtotal" context "Order subtotal" %}</h3>
      </div>
      <div class="col-4">
        <h3 class="text-right cart-subtotal"
           data-value="{% gross cart_total %}"
           {% if local_cart_total %}data-value-local="{% gross local_cart_total %}"{% endif %}>
          {% spaceless %}
            {% gross cart_total html=True %}
            {% if local_cart_total %}
              <br>
              <small>
                &asymp;
                {% gross local_cart_total html=True %}
              </small>
            {% endif %}
          {% endspaceless %}
        </h3>
      </div>
    </div>
  </div>
  <div class="last table__row cart__delivery-info">
    <div class="row">
      <div class="col-7 cart__total__subtotal deliveryform" data-csrf="{{ csrf_token }}">
        <div class="row">
          <div class="col-12 col-md-4">
            <p>{% trans "Shipping cost for:" context "Cart shipping cost form" %}</p>
          </div>
          <div class="col-12 col-md-8">
            {{ country_form.country }}
          </div>
        </div>
      </div>
      <div class="col-5">
        <div class="row">
          <div class="col-md-12 col-12 text-right">
            <p class="cart__delivery-info__price">
              {% if default_country_options %}
                {% price_range default_country_options %}
              {% endif %}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endif %}
<div class="cart__total">
  <div class="row">
    <div class="col-8 cart__total__subtotal">
      <h3>{% trans "Total" context "Order subtotal" %}</h3>
    </div>
    <div class="col-4">
      {% spaceless %}
        <h3 class="text-right cart-total"><span>{% price_range total_with_shipping %}</span>
          {% if local_total_with_shipping %}
            <br>
            <small>
              &asymp;
              {% price_range local_total_with_shipping %}
            </small>
          {% endif %}
        </h3>
      {% endspaceless %}
    </div>
  </div>
</div>

templates/cart/index.html
{% extends "base.html" %}
{% load gross from prices_i18n %}
{% load i18n %}
{% load staticfiles %}
{% load render_bundle from webpack_loader %}
{% load get_thumbnail from product_images %}

{% block title %}Shopping Cart{% endblock %}


{% block content %}

<div id="content" class="site-content" tabindex="-1" >
  <div class="col-full">
    <div class="pizzaro-breadcrumb">
      <nav class="woocommerce-breadcrumb" >
        <a href="{% url "home" %}">Home</a>
        <span class="delimiter"><i class="po po-arrow-right-slider"></i></span>Shopping Cart
      </nav>
    </div>
    <div id="primary" class="content-area">
      <main id="main" class="site-main">
        {% if cart_lines %}
        <div class="pizzaro-order-steps hidden-xs">
          <ul>
            <li class="cart">
              <span class="step" style="background-color:#c00a27;">1</span>Shopping Cart
            </li>
            <li class="checkout">
              <span class="step">2</span>Checkout
            </li>
            <li class="complete">
              <span class="step">3</span>Order Complete
            </li>
          </ul>
        </div>
        {% endif %}
        <center>
          <div id="post-8" class="post-8 page type-page status-publish hentry">
            <div class="entry-content">
              <div class="woocommerce">
                {% if not cart_lines %}
                <div class="cart__empty">
                  <img src="{% static 'images/empty_bag.gif' %}" style="max-width:500px;" />
                  <h2>{% trans "There are no products in your shopping cart." context "Empty cart message" %}</h2>
                </div>
                {% else %}
                <table class="shop_table shop_table_responsive cart" >
                  <thead>
                    <tr>
                      <!-- <th class="product-remove">&nbsp;</th> -->
                      <th class="product-thumbnail">&nbsp;</th>
                      <th class="product-name">Product</th>
                      <th class="product-quantity">Quantity</th>
                      <th class="product-subtotal">Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for line in cart_lines %}
                    <tr class="cart__line{% if forloop.last %} last{% endif %} table__row cart_item">
                      <div class="cart__line__product">
                        <td class="product-thumbnail">
                          <a href="{{line.variant.product.get_absolute_url}}">
                            <img width="180" height="180" src="{{line.variant.product.get_first_image.url}}" alt=""/>
                          </a>
                        </td>
                        <td class="product-name" data-title="Product">
                          <a href="{{line.variant.product.get_absolute_url}}">{{line.variant.product.name}}</a>
                          <dl class="variation">
                            <dd class="variation-Baseprice">
                              <p><span class="woocommerce-Price-amount amount">{{line.variant}}</span></p>
                            </dd>
                          </dl>
                        </td>
                      </div>
                    <td class="table__row product-quantity" data-title="Quantity">
                      <div class="cart__line__quantity">
                        <label>Quantity</label>
                          <form role="form" action="{% url "cart:update-line" variant_id=line.variant.pk %}" method="post" class="form-cart">
                            <span class="cart-item-delete">
                              <img src="{% static "images/delete.svg" %}" height="20px" width="20px" />
                            </span>
                            <div class="{% if form.quantity.errors %} has-error{% endif %}" tabindex="-1" style="margin-top:-27px; margin-left:25px;">
                              {{line.form.quantity}}
                            </div>
                            {% csrf_token %}
                          </form>
                          <small class="cart__line__quantity-error text-danger"></small>
                        </div>
                    </td>
                    <td>
                      <div class="cart-item-price" data-product-id="{{line.variant.pk}}">
                        {% gross line.get_total html=True %}
                      </div>
                    </td>
                </tr>
                {% endfor %}
                <div class="cart__subtotal" style="display:none;">
                </div>
                <tr>
                  <td colspan="6" class="actions">
                    <div class="wc-proceed-to-checkout">
                      <a href="{{category.get_absolute_url}}" class="checkout-button button alt wc-forward">Continue Shopping</a>
                      <a href="{% url "checkout:login" %}" class="checkout-button button alt wc-forward">Proceed to Checkout</a>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
            {% endif %}
          </div>
        </div>
      </div>
    </center>
  </main>
</div>
</div>
</div>

{% endblock content %}



{% comment %}

<div id="content" class="site-content" tabindex="-1" >
  <div class="col-full">
    <div class="pizzaro-breadcrumb">

    </div>
    <center>
      <!-- .woocommerce-breadcrumb -->
      <div id="primary" class="content-area">
        <main id="main" class="site-main" >
          {% if cart_lines %}
          <div class="table__header d-none d-md-block">
            <div class="row">
              <div class="col-md-7">
                <small>{% trans "Product" context "Cart table header" %}</small>
              </div>
              <div class="col-md-3">
                <small>{% trans "Quantity" context "Cart table header" %}</small>
              </div>
              <div class="col-md-2 text-right">
                <small>{% trans "Price" context "Cart table header" %}</small>
              </div>
            </div>
          </div>
          {% for line in cart_lines %}
          <div class="cart__line{% if forloop.last %} last{% endif %} table__row">
            <div class="row">
              <div class="col-7 cart__line__product">
                <a class="link--clean" href="{{ line.variant.get_absolute_url }}">
                  <img src="{% get_thumbnail line.variant.product.images.first.image method="crop" size="60x60" %}"
                  srcset="{% get_thumbnail line.variant.product.images.first.image method="crop" size="60x60" %} 1x, {% get_thumbnail line.variant.product.images.first.image method="crop" size="120x120" %} 2x"
                  alt="">
                  <p>{{ line.variant.product }}
                    <br><small>{{ line.variant }}</small></p>
                  </a>
                </div>
                <div class="col-5">
                  <div class="row">
                    <div class="cart__line__quantity col-md-7 col-12">
                      <form role="form" action="{% url "cart:update-line" variant_id=line.variant.pk %}" method="post" class="form-cart">
                        <div class="{% if form.quantity.errors %} has-error{% endif %}" tabindex="-1">
                          {{ line.form.quantity }}
                        </div>
                        {% csrf_token %}
                      </form>
                      <span class="cart-item-delete">
                        <svg data-src="{% static "images/delete.svg" %}" height="20px" width="20px" />
                      </span>
                      <small class="cart__line__quantity-error text-danger"></small>
                    </div>
                    <div class="cart-item-price col-md-5 col-12" data-product-id="{{ line.variant.pk }}">
                      <p class="text-right">{% gross line.get_total html=True %}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            <div class="cart__subtotal">
              {% include 'cart/_subtotal_table.html' %}
            </div>
            <div class="row">
              <div class="col-md-12">
                <a href="{% url "checkout:login" %}" class="btn primary float-right cart__submit">
                  {% trans "Checkout" context "Cart primary action" %}
                </a>
              </div>
            </div>
            {% else %}
            <div class="cart__empty">
              <img src="{% static 'images/pirate_cart.png' %}"
              srcset="{% static 'images/pirate_cart.png' %} 1x, {% static 'images/pirate_cart2x.png' %} 2x">
              <h2>{% trans "There are no products in your shopping cart." context "Empty cart message" %}</h2>
            </div>
            {% endif %}
          </main><!-- #main -->
        </div>
      </center>
      <!-- #post-## -->
    </div>
    <!-- #primary -->
  </div>

  {% endcomment %}

  {% block scripts %}
  <script type="text/javascript">
  $("#id_quantity").on("change", function(){
    setTimeout(function(){
      window.location.reload();
    },500)
  })
  </script>
  {% endblock scripts %}