saleor/dashboard/customer/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.customer_list, name='customers'),
    url(r'^(?P<pk>[0-9]+)/$', views.customer_details, name='customer-details'),
    url(r'^(?P<pk>[0-9]+)/promote/$', views.customer_promote_to_staff,
        name='customer-promote')
]

saleor/dashboard/group/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.group_list, name='group-list'),
    url(r'^group-create/$', views.group_create, name='group-create'),
    url(r'^(?P<pk>[0-9]+)/$', views.group_details, name='group-details'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.group_delete, name='group-delete')
]

saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.order_list, name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change-stock/$',
        views.orderline_change_stock, name='orderline-change-stock'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/add-variant/$',
        views.add_variant_to_group, name='add-variant-to-group'),
    url(r'^(?P<order_pk>\d+)/invoice/$',
        views.order_invoice, name='order-invoice'),
    url(r'^(?P<group_pk>\d+)/packing-slips/$',
        views.order_packing_slip, name='order-packing-slips'),
]

saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .staff.urls import urlpatterns as staff_urls
from .group.urls import urlpatterns as groups_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .discount.urls import urlpatterns as discount_urls
from .search.urls import urlpatterns as search_urls
from .sites.urls import urlpatterns as site_urls
from .shipping.urls import urlpatterns as shipping_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^staff/', include(staff_urls)),
    url(r'^groups/', include(groups_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^settings/', include(site_urls)),
    url(r'^shipping/', include(shipping_urls)),
    url(r'^style-guide/', core_views.styleguide, name='styleguide'),
    url(r'^search/', include(search_urls)),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import JavaScriptCatalog
from django.contrib import admin
from graphene_django.views import GraphQLView

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^superadmin/', admin.site.urls),
    url(r'^account/', include(registration_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^impersonate/', include('impersonate.urls')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^profile/',
        include((userprofile_urls, 'profile'), namespace='profile')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search')),
    url(r'^mobile/', include("saleor.mobile.urls")),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Category
from ..views import staff_member_required
from .filters import CategoryFilter
from .forms import CategoryForm


@staff_member_required
@permission_required('product.view_category')
def category_list(request):
    categories = Category.tree.root_nodes().order_by('name')
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {'categories': categories, 'filter': category_filter}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-detail', pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form, 'path': path}
    return TemplateResponse(request, 'dashboard/category/form.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-detail', pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status, 'path': path}
    template = 'dashboard/category/form.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.view_category')
def category_detail(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by('name')
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {'categories': categories, 'path': path, 'root': root,
           'filter': category_filter}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Removed category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-detail', kwargs={'pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-detail', pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(
        request, 'dashboard/category/modal/confirm_delete.html', ctx)

saleor/dashboard/customer/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.db.models import Count, Max
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...userprofile.models import User
from ..views import staff_member_required
from .filters import UserFilter


@staff_member_required
@permission_required('userprofile.view_user')
def customer_list(request):
    customers = (
        User.objects
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .order_by('email'))
    customer_filter = UserFilter(request.GET, queryset=customers)
    customers = get_paginator_items(
        customer_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {'customers': customers, 'filter': customer_filter}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
@permission_required('userprofile.view_user')
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related(
        'default_billing_address', 'default_shipping_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)


@staff_member_required
@permission_required('userprofile.edit_staff')
@permission_required('userprofile.edit_user')
def customer_promote_to_staff(request, pk):
    customer = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        customer.is_staff = True
        customer.save()
        msg = pgettext_lazy(
            'Dashboard message',
            'Customer %s promoted to staff member') % customer
        messages.success(request, msg)
        return redirect('dashboard:customer-details', pk=customer.pk)
    return TemplateResponse(
        request, 'dashboard/customer/modal/confirm_promote.html',
        {'customer': customer})

saleor/dashboard/group/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Group
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ..views import staff_member_required
from .filters import GroupFilter
from .forms import GroupPermissionsForm


@staff_member_required
@permission_required('userprofile.view_group')
def group_list(request):
    groups = (Group.objects.all().prefetch_related('permissions')
              .order_by('name'))
    group_filter = GroupFilter(request.GET, queryset=groups)
    groups = [{'name': group, 'permissions': group.permissions.all()}
              for group in group_filter.qs]
    groups = get_paginator_items(
        groups, settings.DASHBOARD_PAGINATE_BY, request.GET.get('page'))
    ctx = {'groups': groups, 'filter': group_filter}
    return TemplateResponse(request, 'dashboard/group/list.html', ctx)


@staff_member_required
@permission_required('userprofile.edit_group')
def group_create(request):
    group = Group()
    form = GroupPermissionsForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(
            request,
            pgettext_lazy('Dashboard message',
                          'Created group'))
        return redirect('dashboard:group-list')
    ctx = {'group': group, 'form': form}
    return TemplateResponse(request, 'dashboard/group/detail.html', ctx)


@staff_member_required
@permission_required('userprofile.edit_group')
def group_details(request, pk):
    group = Group.objects.get(pk=pk)
    form = GroupPermissionsForm(request.POST or None, instance=group)
    if form.is_valid():
        form.save()
        messages.success(
            request,
            pgettext_lazy('Dashboard message', 'Updated group %s') % group.name
        )
        return redirect('dashboard:group-list')
    ctx = {'group': group, 'form': form}
    return TemplateResponse(request, 'dashboard/group/detail.html', ctx)


@staff_member_required
@permission_required('userprofile.edit_group')
def group_delete(request, pk):
    group = get_object_or_404(Group, pk=pk)
    if request.method == 'POST':
        group.delete()
        messages.success(
            request,
            pgettext_lazy('Dashboard message', 'Removed group %s') % group
        )
        return redirect('dashboard:group-list')
    return TemplateResponse(
        request, 'dashboard/group/modal/confirm_delete.html', {'group': group})

saleor/dashboard/search/views.py
from django.conf import settings
from django.http import Http404
from django.shortcuts import render

from ..views import staff_member_required
from .forms import DashboardSearchForm


def limit_results(*results):
    '''Pass-through only first few best items for each result query'''
    limit = settings.DASHBOARD_SEARCH_LIMIT
    return (qs[:limit] for qs in results)


def get_results(request, form):
    user = request.user
    results = form.search()
    products = results['products']
    orders = results['orders']
    users = results['users']
    if not user.has_perm('order.view_order'):
        orders = orders.none()
    if not user.has_perm('userprofile.view_user'):
        users = users.none()
    return limit_results(products, orders, users)


@staff_member_required
def search(request):
    if not settings.ENABLE_SEARCH:
        raise Http404('No such page!')
    form = DashboardSearchForm(data=request.GET or None)
    query = ''
    users = []
    products = []
    orders = []
    if form.is_valid():
        products, orders, users = get_results(request, form)
        query = form.cleaned_data['q']
    ctx = {
        'form': form,
        'query': query,
        'products': products,
        'orders': orders,
        'users': users,
        'query_string': '?q=%s' % query}
    return render(request, 'dashboard/search/results.html', ctx)

templates/dashboard/customer/detail.html
{% extends "dashboard/base.html" %}
{% load prices_i18n %}
{% load i18n %}
{% load materializecss %}
{% load status %}
{% load staticfiles %}

{% block title %}
  {{ customer }} - {% trans "Customers" context "Dashboard customers list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-customers{% endblock %}

{% block menu_customers_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:customers" as url %}
  {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:customers" %}">
        {% trans "Customers" context "Dashboard customers list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:customers" %}">
        <svg data-src="{% static "dashboard/images/arrow_left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li><span class="breadcrumbs--elipsed-item">{{ customer }}</span></li>
  </ul>
{% endblock %}


{% block header_extra %}
  {% if customer.pk and not customer.is_staff and perms.userprofile.edit_staff and perms.userprofile.edit_user or perms.userprofile.impersonate_user %}
    <a class="dropdown-button right" href="#" data-activates="context-menu" data-constrainwidth="false">
      <svg data-src="{% static "dashboard/images/more_vert.svg" %}" height="24" width="24" />
    </a>
    <ul id="context-menu" class="dropdown-content">
      {% if perms.userprofile.edit_user and perms.userprofile.edit_staff %}
        <li>
          <a href="#base-modal" data-href="{% url 'dashboard:customer-promote' pk=customer.pk %}"
          class="modal-trigger-custom">
            {% trans 'Promote to staff' context 'Customer promote to staff member action' %}
          </a>
        </li>
      {% endif %}
      {% if perms.userprofile.impersonate_user %}
        <li>
          <a href="{% url 'impersonate-start' uid=customer.pk %}">Impersonate customer</a>
        </li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}


{% block content %}
  <div class="row">
    <div class="col s12 l8">
      <div class="card">
        <div class="data-table-header{% if not customer_orders %} data-table-header--no-data{% endif %}">
          <h5 class="data-table-title">
            {% trans "Order history" context "Customer orders table title" %}
          </h5>
        </div>
        {% if customer_orders %}
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table">
              <thead>
                <tr>
                  <th>
                    {% trans "Number" context "Customer orders table header" %}
                  </th>
                  <th>
                    {% trans "Placed on" context "Customer orders table header" %}
                  </th>
                  <th>
                    {% trans "Order status" context "Customer orders table header" %}
                  </th>
                  <th class="right-align">
                    {% trans "Total" context "Customer orders table header" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for order in customer_orders %}
                  <tr data-action-go="{% if perms.order.view_order %}{% url 'dashboard:order-details' order_pk=order.pk %}{% endif %}">
                    <td>
                      {{ order }}
                    </td>
                    <td>
                      {{ order.created }}
                    </td>
                    <td>
                      {% render_status order.status order.get_status_display %}
                    </td>
                    <td class="right-align">
                      {% gross order.get_total html=True %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <div class="card-content card-content--no-data">
            <p>
              {% trans "No orders found." context "Empty customer orders table message" %}
            </p>
          </div>
        {% endif %}
      </div>
    </div>

    <div class="col s12 l4">
       <div class="row">
        <div class="col s12 m6 p6 l12">
          <div class="card equal-height-on-med">
            <div class="card-content">
              <span class="card-title black-text">
                {% trans "Default shipping address" context "Customer default shipping address card title" %}
              </span>
              {% if customer.default_shipping_address %}
                {% with customer.default_shipping_address as address %}
                  {% include 'dashboard/includes/_address.html' with address=address only %}
                {% endwith %}
              {% else %}
                <div>{% trans "No default shipping address." context "Customer without default shipping address message" %}</div>
              {% endif %}
              <svg data-src="{% static "dashboard/images/email.svg" %}" width="14" height="14" />
              <a href="mailto:{{ customer.email }}">
                {{ customer.email }}
              </a>
            </div>
          </div>
        </div>
        <div class="col s12 m6 p6 l12">
          <div class="card equal-height-on-med">
            <div class="card-content">
              <span class="card-title black-text">
                {% trans "Default billing address" context "Customer default billing address card title" %}
              </span>
              {% if customer.default_billing_address %}
                {% with customer.default_billing_address as address %}
                  {% include 'dashboard/includes/_address.html' with address=address only %}
                {% endwith %}
              {% else %}
                <div>
                  {% trans "No default billing address." context "Customer without default billing address message" %}
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/customer/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load prices_i18n %}
{% load get_sort_by_toggle from shop %}
{% load materializecss %}
{% load utils %}

{% block title %}
  {% trans "Customers" context "Dashboard customers list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-customers{% endblock %}

{% block menu_customers_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
      {% trans "Customers" context "Dashboard customers list" %}
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      {% if customers %}
        <div class="card">
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table">
              <thead>
                <tr>
                  {% get_sort_by_toggle 'name' as toggle %}
                  <th class="{% if toggle.is_active %}active{% endif %}">
                    <a href="{{ toggle.url }}">
                      <svg data-src="{{ toggle.sorting_icon }}" />
                      {% trans "Name" context "Customers table header" %}
                    </a>
                  </th>
                  {% get_sort_by_toggle 'email' as toggle %}
                  <th class="{% if toggle.is_active %}active{% endif %}">
                    <a href="{{ toggle.url }}">
                      <svg data-src="{{ toggle.sorting_icon }}" />
                      {% trans "Email" context "Customers table header" %}
                    </a>
                  </th>
                  {% get_sort_by_toggle 'location' as toggle %}
                  <th class="{% if toggle.is_active %}active{% endif %}">
                    <a href="{{ toggle.url }}">
                      <svg data-src="{{ toggle.sorting_icon }}" />
                      {% trans "Location" context "Customers table header" %}
                    </a>
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for customer in customers %}
                  <tr data-action-go="{% url "dashboard:customer-details" pk=customer.pk %}">
                    {% with customer.default_billing_address as default_address %}
                      <td>
                        {% if default_address %}
                          {{ default_address.first_name }} {{ default_address.last_name }}
                        {% else %}
                          -
                        {% endif %}
                      </td>
                      <td>
                        {{ customer.email }}
                      </td>
                      <td>
                        {% if default_address %}
                          {{ default_address.city }}, {{ default_address.get_country_display }}
                        {% else %}
                          -
                        {% endif %}
                      </td>
                    {% endwith %}
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      {% else %}
        <div class="card-content card-content--no-data not-found">
          <p class="grey-text">
            {% trans "No customers found." context "Empty customers table message" %}
          </p>
        </div>
      {% endif %}
      {% paginate customers %}
    </div>
    <div class="col s12 l3" id="filters">
      {% add_filters filter %}
    </div>
  </div>
{% endblock %}